### ISSUE TITLE
Django 3.1 support is missing. 

### ISSUE THREAD

**Issue by ak55mm** [timonweb/django-clearcache#3]
**We are on the latest django 3.1.1.** 

Trying to install django-clearcache gives the following error:
`django-clearcache 1.0.1 requires django<3.1,>=2.2, but you'll have django 3.1.1 which is incompatible.`

**Comment by Schwankenson** [comment]
Same here...

**Comment by timonweb** [comment]
Hi all, thank you for your feedback and nudges. I'm glad to see people using clearcache. I've just released v. `1.1.0` that adds Python 3.9 and Django 3.1 support. Be safe all 😷.

**Comment by Schwankenson** [comment]
Thank you for this quick action and the app. In my opinion, this should be in the django core.

Unfortunately, I still get the same error. I think there is still the dependency

`django = ">=2.2,<3.1"`

in https://github.com/timonweb/django-clearcache/blob/master/pyproject.toml

**Comment by fabianhoward** [comment]
After installing Django-3.1.2 I'm now getting `django-clearcache 1.1.0 requires django<3.1,>=2.2, but you'll have django 3.1.2 which is incompatible.`

**Comment by timonweb** [comment]
Ah, sorry about, mixed that part. Fixed, released 1.1.1, let me know if all is well.

**Comment by fabianhoward** [comment]
Seems perfect thanks.

**Comment by Schwankenson** [comment]
Works perfectly. Thank you!
